### ISSUE TITLE
Implement Ads Api - Business Manager endpoints

### ISSUE THREAD

**Issue by momer** [moviepilot/zuck#13]
Afternoon all,

Thanks for your work thus far on the project. I'm likely going to build in this functionality over the next week or few - pending on how much time I can allocate towards it. Is this something you'd be interested in merging in, or would you prefer to keep the Ads Api - Business Manager endpoints [[0]] out of the gem?

[0]: https://developers.facebook.com/docs/reference/ads-api/business-systemuser/v2.2

**Comment by momer** [comment]
Unfortunately, my employer preferred that to keep the timeline slim and the scope small, I managed my own service objects etc. for this.

**Comment by jayniz** [comment]
@momer alright, too bad :) if you still use the gem make sure to update it though, the it has changes relevant to the ads api updates
