### ISSUE TITLE
date parameters in ads stats

### ISSUE THREAD

**Issue by runa** [moviepilot/zuck#9]
Hello :) 
I'm extending Zuck's to support [adstatistics](https://developers.facebook.com/docs/reference/ads-api/adstatistics).

To set a specific date range, I need to enter the start and end unix timestamps in the requested graph URL 
> To query statistics within a particular time windows, append a start and stop time in the UNIX timestamp to the URL path as follows:
> https://graph.facebook.com/act_{ad_account_id}/stats/1320451200/1321315200?access_token=___

I saw that the URL is built based on the ancestor and the `list_path`, but I'm not sure how to add some dynamic options there (report start and finish).

This is how my AdCampaignStat looks like:
```ruby
module Zuck
  class AdCampaignStat < RawFbObject

    known_keys :name,
               :objective,
               :campaign_group_status,
               :buying_type,
               :end_time,
               :id,
               :adgroups,
               :is_completed

    parent_object :ad_account
    list_path     :adcampaignstats
    connections   :ad_groups

  end
end
```

**Comment by jayniz** [comment]
hey @runa, should we close this?

**Comment by runa** [comment]
yeah, I'm currently hitting the Graph API directly for this..
